"""Write fixtures/golden/PLAY_TYPES.md: every distinct play `type` across the golden
games, with counts, and how often each appears as a scoring play. Reads the saved
fixtures only. No network, no key. This is discovery for task 2.6b: it lists the
vocabulary, it does not classify it.
"""
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "fixtures" / "golden"


def main():
    counts, scoring, periods, games = Counter(), Counter(), Counter(), []
    samples = {}
    for d in sorted(p for p in ROOT.iterdir() if p.is_dir()):
        f = d / "plays.json"
        if not f.exists():
            continue
        plays = json.loads(f.read_text())["data"]
        games.append((d.name, len(plays), max((p.get("period") or 0) for p in plays)))
        for p in plays:
            t = p.get("type") or "(none)"
            counts[t] += 1
            if p.get("scoring_play"):
                scoring[t] += 1
            periods[p.get("period")] += 1
            samples.setdefault(t, p.get("text") or "")
    out = ["# Play types in the golden set", "",
           "Generated by `tools/play_types.py` from `fixtures/golden/*/plays.json`. Discovery only:",
           "the classifier in task 2.6b is written against this list, not guessed.", "",
           "| Game | Plays | Max period |", "|---|---|---|"]
    out += ["| %s | %d | %d |" % g for g in games]
    out += ["", "| Type | Count | Scoring | Example text |", "|---|---|---|---|"]
    for t, n in counts.most_common():
        ex = samples[t].replace("|", "/")[:70]
        out.append("| %s | %d | %d | %s |" % (t, n, scoring[t], ex))
    out += ["", "%d distinct types across %d plays." % (len(counts), sum(counts.values()))]
    (ROOT / "PLAY_TYPES.md").write_text("\n".join(out) + "\n")
    print("wrote PLAY_TYPES.md: %d types" % len(counts))


if __name__ == "__main__":
    main()
